# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[background]
path = "/etc/greetd/wallpaper.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "BreezeX-Black"
font_name = "Roboto 16"
icon_theme_name = "Papirus-Dark"
theme_name = "adw-gtk3-dark"
